FROM node:20.5.1

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install Next.js and other dependencies
RUN npm install

# Copy the entire project into the container
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
